[project]
name = "people-register-infrastructure"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aws-cdk-lib==2.194.0",
    "boto3>=1.34.0",
    "constructs>=10.0.0,<11.0.0",
    "pydantic>=2.7.0",
]
